name: "AMIBuildScript"
description: "Build script for custom ImageBuilder AMI"
schemaVersion: 1.0

parameters:
  - PARAMETERSTORE_NAME:
      type: string
      description: Systems Manager Parameter Store name
  - INSTANCE_NAME:
      type: string
      description: Instance name
  - S3_SYSTEM_BUCKET:
      type: string
      description: S3 System Bucket name
      
phases:
  - name: build
    steps:
      - name: AMIBuildScriptDownload
        action: S3Download
        onFailure: Abort
        maxAttempts: 1
        inputs:
          - source: 's3://{{ S3_SYSTEM_BUCKET }}/imagebuilder/build.sh'
            destination: '/tmp/build.sh'
      - name: AMIBuildScriptStart
        action: ExecuteBash
        onFailure: Abort
        maxAttempts: 1
        inputs:
          commands:
            - 'export  _PARAMETERSTORE_NAME={{ PARAMETERSTORE_NAME }}'
            - 'export  _INSTANCE_NAME={{ INSTANCE_NAME }}'
            - 'bash {{ build.AMIBuildScriptDownload.inputs[0].destination }}'
      - name: AMIBuildScriptDelete
        action: DeleteFile
        inputs:
          - path: '{{ build.AMIBuildScriptDownload.inputs[0].destination }}'
              
              
  - name: test
    steps:
      - name: AMITestScriptDownload
        action: S3Download
        onFailure: Abort
        maxAttempts: 1
        inputs:
          - source: 's3://{{ S3_SYSTEM_BUCKET }}/imagebuilder/test.sh'
            destination: '/tmp/test.sh'
      - name: AMITestScriptStart
        action: ExecuteBash
        onFailure: Abort
        maxAttempts: 1
        inputs:
          commands:
            - 'export  _PARAMETERSTORE_NAME={{ PARAMETERSTORE_NAME }}'
            - 'export  _INSTANCE_NAME={{ INSTANCE_NAME }}'
            - 'bash {{ test.AMITestScriptDownload.inputs[0].destination }}'
      - name: AMITestScriptDelete
        action: DeleteFile
        inputs:
          - path: '{{ test.AMITestScriptDownload.inputs[0].destination }}'
          
